name: HitWine
favicon: null
layout_spectrum: 0.2020594603382051
typography_spectrum: 0.19306212337687612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8228111048229039
  lightness: 0.1313784383237362
  saturation: 0.97484195465222
  rhythmicContrast: 0.3699047926347703
purpose: []
